version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install virtualenv
      - pip install coverage
      - python -m virtualenv env
      - source env/bin/activate
      - pip install coverage
      - pip install db-sqlite3
      - pip install install pysqlite3
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py runserver
      - python manage.py test
  post_build:
    commands:
      - echo "Build complete"

