version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python -m pip install --upgrade pip
      - pip install virtualenv
      - pip install coverage
      - python -m virtualenv env
      - source env/bin/activate
      - pip install coverage
      - pip install db-sqlite3
      - pip install pysqlite3
      - pip install pysqlite3-binary
      - pip install -r requirements.txt
  build:
    commands:
      - echo "build"
      - python manage.py collectstatic --noinput
  post_build:
    commands:
      # Deploy to Elastic Beanstalk
      - eb init -p python-3.7 <your-application-name> --region <your-region>

