name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Tests and Coverage
      run: |
        coverage run --source='.' manage.py test
    - name: Generate Coverage Report
      run: |
       coverage report
    - name: Check Coverage
      run: |
       coverage report --fail-under=80
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "python-app-ci-cd"
        heroku_email: "alejoferna2301@gmail.com"
        branch: "master"
        buildpack: "heroku/python"
        extra: |
          python manage.py collectstatic --noinput
